dataset_builder: &ds_builder
    img_shape: [300, 200, 3]

train:
    dataset_builder:
        <<: *ds_builder
    batch_size: 256
    # Number of epochs to train.
    epochs: 20
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0

eval:
    dataset_builder:
        <<: *ds_builder
    batch_size: 128